### ISSUE TITLE
[REFACTOR] To-do List for Reactor / Organize Project

### ISSUE THREAD

**Issue by Guuzzeji** [Guuzzeji/CSCI-367-Group-Project#15]
# About

This is a quick to-do list outlining the main tasks required for restructuring the project.

## To-do

- [x] Remove duplicate files.
- [x] Resolve CORS error.
- [x] Address missing `bookid` return from SQL search.
- [x] Enhance documentation for both the system and API.
- [x] Streamline running process by removing `.env` requirements.
- [x] Refactor codebase for clarity and add explanatory comments.
- [x] ~~Add `requirements.txt` for Python~~
- [x] Add stuff to main readme.md
- [x] Add error handlers for all API request to return 503 errors if server were to crash / some type of error were to happen.

## Optional

- [ ] Do some SQL optimization (indexing for quicker look-ups)
